global:
  scrape_interval: 15s  # How often Prometheus colllects metrics
  evaluation_interval: 15s #How often it evaluates alert rules

scrape_configs:
  - job_name: 'prometheus'
    static_cocnfigs:
      - targets: ['localhost:9090'] # Prometheus scrapes itself too